modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ForgeEssentials/ForgeEssentials/issues"

[[mods]]
    modId="forgeessentialsclient"
    version="${version}"
    displayName="${mod_name}"
    updateJSONURL="https://raw.githubusercontent.com/ForgeEssentials/UpdateChecker/main/ClientVersions.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/forge-essentials-client"
    logoFile="logo.png"
    credits="Thanks to everyone who has helped us so far."
    authors="AbrarSyed, luacs1998, olee, dries007, Malkierian, Spacebuilder2020, maximuslotro/MaximustheMiner, And a few others"
    description='''Client addon for ForgeEssentials (optional)'''

[[dependencies.forgeessentialsclient]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.forgeessentialsclient]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"