# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - '**'
  pull_request: {}
  release:
    types: released
env:
  BUILD_NUMBER: 'UNOFFICIAL-${{ github.sha }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Build Number from Release
        if: ${{ github.event.release }}
        run: |
          FULL_VERSION=($(echo ${{ github.event.release.tag_name }} | tr "." "\n"))
          echo "BUILD_NUMBER=${FULL_VERSION[2]}" >> $GITHUB_ENV
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: |
         chmod +x gradlew
         ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ env.BUILD_NUMBER }}
          path: ./build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: ts-files-${{ github.sha }}
          path: jscripting/*.d.ts
      - env:
          CF_APIKEY: ${{ secrets.CF_APIKEY }}
          CHANGE_LOG: ${{ github.event.release.body }}
        if: ${{ github.event.release }}
        run: |
          mkdir ./tmp
          cp ./build/libs/*-server.jar ./tmp
          chmod +x gradlew
          ./gradlew curseforge
